@startuml

title __MANAGER's Class Diagram__\n

  namespace manager {
    class manager.Admin {
        ~ deletedData : ArrayList<Item>
        ~ userSavedData : ArrayList<Item>
        - usersLocalDir : String
        + Admin()
        + convertToHashMap()
        + getActiveUsers()
        + getAllDeletedHistory()
        + getAllRegisteredUsers()
        + getDeletedData()
        + getSelectedUserData()
        + loadUserDeletedDataById()
        + logActivity()
        + readFileItems()
        + recoverSelectedUserDeletedData()
        + restoreAllDeletedHistory()
        + restoreSelectedResult()
        + saveDeletedHistory()
        - addSearchKeyToUser()
        - extractItem()
        - getUsersIds()
        - saveDeletedHistory()
    }
  }
  

  namespace manager {
    class manager.App {
        {static} + email : Email
        {static} + emailAddress : String
        {static} + emailAndPrint : boolean
        {static} + flagError : boolean
        {static} + inputFilename : String
        {static} + outputFilename : String
        {static} + print : boolean
        {static} + results : HashMap<String, ArrayList<Item>>
        {static} + sendEmail : boolean
        {static} + startGui : boolean
        {static} + createEmailReport()
        {static} + displayToUser()
        {static} + executeFlags()
        {static} + isFileName()
        {static} + isValidEmailAddress()
        {static} + main()
        {static} + parseFlags()
        {static} + printToFile()
        {static} + readSearchQueries()
        {static} + requestDataFromEtsy()
        {static} + requestDataFromEtsy()
    }
  }
  

  namespace manager {
    class manager.UserSession {
        - baseDir : String
        - currentSearch : String
        - emailList : ArrayList<Item>
        - isGuestUser : Boolean
        - isViewingEmailReport : Boolean
        - searchHistory : HashMap<String, String>
        - searches : HashMap<String, ArrayList<Item>>
        - userSearchKeyDir : String
        + UserSession()
        + addCurrentSearchToEmailReport()
        + addItemToEmailReport()
        + deleteCurrentSearch()
        + deleteEmailReport()
        + deleteItemFromEmailReport()
        + deleteSingleResult()
        + downloadItemImg()
        + getAllSearches()
        + getCurrentSearch()
        + getEmailList()
        + getResultsFromHistory()
        + getSearchHistory()
        + getSearches()
        + getUser()
        + isGuestUser()
        + isViewingEmailReport()
        + loadHistory()
        + logActivity()
        + logData()
        + logData()
        + search()
        + searchOnEtsy()
        + setIsGuestUser()
        + setUser()
        + sortByDateASC()
        + sortByDateDESC()
        + sortByPrice()
        + storeUserActivity()
        + toString()
        - getNextImgId()
        - incrementImgIdByOne()
    }
  }
  

  manager.UserSession o-- core.User : user


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
